[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "align"
dynamic = ["version"]
description = "Needleman-Wunsch global pairwise sequence alignment"
dependencies = ["numpy"]
